# roles/wordpress/tasks/salt.yml
# Download a new salt
---
- name: Download Salts
  get_url:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    dest: "{{ wordpress_directory }}/wp-salts.php"
    seuser: system_u
    setype: httpd_sys_script_exec_t
    force: false
  notify: restart httpd
  tags: wordpress

- name: Insert PHP start tag in Salts file
  lineinfile:
    dest: "{{ wordpress_directory }}/wp-salts.php"
    line: '<?php'
    state: present
    insertbefore: BOF
  notify: restart httpd
  tags: wordpress

- name: Insert PHP end tag in Salts file
  lineinfile:
    dest: "{{ wordpress_directory }}/wp-salts.php"
    line: '?>'
    state: present
    insertafter: EOF
  notify: restart httpd
  tags: wordpress
