# roles/wordpress/handlers/main.yml
---

- name: restart wordpress
  service:
    name: wordpress
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted
