---
- name: ensure libselinux-python is installed
  yum: name=libselinux-python state=present

- name: ensure policycoreutils-python is installed
  yum: name=policycoreutils-python state=present

- name: configure selinux policy and state
  selinux: conf={{selinux_config|default('/etc/selinux/config')}} policy={{selinux_policy|default('targeted')}} state={{selinux_state|default('enforcing')}}

- name: toggle selinux booleans
  seboolean: name={{item.key}} state={{item.value.state|default('yes')}} persistent={{item.value.persistent|default('yes')}}
  with_dict: "{{selinux_boolean|default({})}}"

- name: configure selinux network port definition
  seport: setype={{item.key}} ports={{item.value.ports}} proto={{item.value.protocol|default('tcp')}} state={{item.value.state|default('present')}}
  with_dict: "{{selinux_ports|default({})}}"

- name: configure selinux fcontext
  shell: /sbin/semanage fcontext {{ '-d' if item.value.state == 'absent' else '-a' }} -f {{item.value.ftype|default('a')}} -t {{item.value.setype}} '{{item.value.file_spec}}'
  with_dict: "{{selinux_fcontext|default({})}}"
