- name: Creating servers in GCE
  gce:
     machine_type: "{{ machine_type }}"
     image: "{{ image }}"
     service_account_email: "{{ service_account_email }}"
     credentials_file: "{{ credentials_file }}"
     project_id: "{{ project_id }}"
     zone: "{{ item.zone }}"
     state: present
     preemptible: false
     instance_names: "{{ item.instance_names }}"
     metadata: '{ "ssh-keys" : "rodrigosouza:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDANxXddzFbed2ol0Z11E1ElkfHpRkM6u/ctR5I6peOm0RxceMjjbgikHrI3G89uFZb467ncehiXwM/ZCqECRTN4+oUZK8Wcs0Uw4X9KH0PGfKx5ORU+94BhOjn6r6Mid2ja9dLfsXysrw1QyKh7p3M2LWmU1XMLboCJ41H/EuPn0PZVGuP5yEOxNjGlCkGw5O/AxERi3U7NWYZ//0OQzLOxV+hrS/JBEKRRBUEGVdYs1TCEG7+LeGWIuF/JI0elbtn35D41jC9c1ONgeYnu8Orr9giQkBmug+/ADemRbzf1J/PnyymtLcEhqkBYSsyiA2sJ6h7uuO/9pM/BuhFsg0p rodrigosouza@mbp-de-rodrigo.grupotba.intra.corp" }'
     tags:
        - http-server
        - https-server
        - all-traffic
  loop:
    - { instance_names: 'webpx01', zone: 'us-east1-b' }
    - { instance_names: 'bdpx01', zone: 'us-central1-c' }
  register: gce_hosts

- debug:
    var: gce_hosts.results[ item ].instance_data[0].public_ip
  with_items:
    - 0
    - 1
        
- name: Waiting for instances to start (checking ssh)
  wait_for:
    delay: 30
    host: "{{ gce_hosts.results[ item ].instance_data[0].public_ip }}"
    port: 22
    state: started
    timeout: 180
  with_items:
    - 0
    - 1
